/** Receipt Rootの不変条件に違反した理由を示す内部Domainコード。 */
export type ReceiptInvariantViolationCode =
  | 'ACTOR_NOT_UPLOADER_OR_OWNER'
  | 'GROUP_REFERENCE_INVALID'
  | 'ITEM_NOT_FOUND'
  | 'ITEM_NOT_BUNDLED'
  | 'CASE_FACT_UNEXPECTED'
  | 'CASE_FACT_REQUIRED'
  | 'CASE_FACT_MISMATCH'
  | 'CASE_REFERENCE_INVALID'
  | 'CASE_VERSION_CONFLICT'
  | 'ITEM_CATEGORY_NOT_CORRECTABLE'
  | 'ITEM_AMOUNT_NOT_CORRECTABLE'
  | 'AFFECTED_CASE_FACTS_MISMATCH'
  | 'CORRECTION_REASON_EMPTY'
  | 'RECEIPT_ID_INVALID'
  | 'BUNDLE_ID_INVALID'
  | 'BUNDLE_NOT_FOUND'
  | 'BUNDLE_MOVE_TARGET_INVALID'
  | 'BUNDLE_WOULD_BE_EMPTY'
  | 'BUNDLE_SNAPSHOT_PAIR_MISMATCH'
  | 'BUNDLE_SNAPSHOT_REFERENCE_INVALID'
  | 'BUNDLE_ALREADY_SELECTED'
  | 'BUNDLE_EDITING_LOCKED'
  | 'RECEIPT_NOT_CONFIRMED'
  | 'BUNDLE_ALREADY_REGISTERED'
  | 'BUNDLE_ITEMS_INVALID'
  | 'ITEM_ALREADY_ASSIGNED'
  | 'BUNDLE_EXPENSE_NOT_INITIAL'
  | 'EXPENSE_ALREADY_PAIRED'
  | 'BUNDLE_EXPENSE_MISMATCH'
  | 'BUNDLE_GROUP_MISMATCH'
  | 'ACTOR_REFERENCE_INVALID'
  | 'RECEIPT_DRAFT_INVALID'
  | 'RECEIPT_NOT_DRAFT'
  | 'VERSION_CONFLICT'
  | 'VERSION_OVERFLOW'
  | 'ACTOR_NOT_UPLOADER'
  | 'UTC_INSTANT_INVALID'
  | 'ITEM_FACT_INVALID'
  | 'CATEGORY_REFERENCE_INVALID'
  | 'OCCURRED_ON_INVALID'
  | 'TOTAL_INVALID'
  | 'ADJUSTMENT_INDEX_INVALID'
  | 'ADJUSTMENT_NOT_BUNDLED'
  | 'ADJUSTMENT_AMOUNT_NOT_CORRECTABLE'
  | 'ADJUSTMENT_INVALID'
  | 'RECEIPT_TOTAL_MISMATCH';

/** 入力値を公開Errorへ漏らさず、Receipt条件を拒否するDomain Error。 */
export class ReceiptInvariantViolation extends Error {
  /**
   * PIIや金額を含まない固定messageと失敗codeを持つ。
   * @param code Receipt条件の違反を識別する内部code。
   */
  constructor(
    /** Callerが入力値を解析せず失敗条件を分類するcode。 */
    readonly code: ReceiptInvariantViolationCode,
  ) {
    super('Receipt invariant violated');
    this.name = 'ReceiptInvariantViolation';
  }
}
