export type GroupInvariantViolationCode =
  | 'IDENTIFIER_EMPTY'
  | 'GROUP_ID_INVALID'
  | 'UTC_INSTANT_INVALID'
  | 'OWNER_MISSING'
  | 'OWNER_DUPLICATED'
  | 'OWNER_MEMBERSHIP_MISMATCH'
  | 'OWNER_NOT_ACTIVE'
  | 'ACTIVE_PARTICIPANT_COUNT_OUT_OF_RANGE'
  | 'PARTICIPANT_DUPLICATED'
  | 'ACTIVE_SUBJECT_DUPLICATED'
  | 'JOIN_ORDER_INVALID'
  | 'JOIN_ORDER_DUPLICATED'
  | 'LEFT_AT_REQUIRED'
  | 'LEFT_AT_NOT_ALLOWED'
  | 'LEFT_AT_BEFORE_JOINED_AT'
  | 'GROUP_NOT_ACTIVE'
  | 'NOT_CURRENT_OWNER'
  | 'TARGET_PARTICIPANT_NOT_ACTIVE'
  | 'ACTOR_PARTICIPANT_MISMATCH'
  | 'OWNER_MUST_TRANSFER_OR_END'
  | 'ALREADY_LEFT'
  | 'GROUP_CAPACITY_REACHED'
  | 'INVITATION_DUPLICATED'
  | 'INVITATION_NOT_FOUND'
  | 'INVITATION_NOT_PENDING'
  | 'INVITATION_EXPIRED'
  | 'INVITATION_TARGET_MISMATCH'
  | 'INVITATION_EXPIRY_INVALID'
  | 'INVITATION_RESULT_INVALID'
  | 'INVITATION_ISSUER_NOT_FOUND'
  | 'INVITATION_ACTION_BEFORE_CREATED'
  | 'ACCESS_POLICY_VERSION_INVALID'
  | 'CLOSE_STATE_INVALID'
  | 'CLOSE_INTENT_ID_INVALID'
  | 'CLOSE_INTENT_MISMATCH'
  | 'CLOSE_RECEIPT_MISMATCH'
  | 'CLOSE_RECEIPT_DUPLICATED'
  | 'CLOSE_RECEIPT_MISSING'
  | 'CLOSE_NOT_ELIGIBLE'
  | 'ARCHIVE_STATE_INVALID';

export class GroupInvariantViolation extends Error {
  constructor(
    readonly code: GroupInvariantViolationCode,
    message: string,
  ) {
    super(message);
    this.name = 'GroupInvariantViolation';
  }
}
